import { facilityHygieneFormItems, healthCheckFormItems, workHygieneFormItems } from "@/constants/hygieneForms";
import {
  getFacilityHygieneRecords,
  getHealthCheckRecords,
  getWorkHygieneRecords,
  saveFacilityHygieneRecords,
  saveHealthCheckRecords,
  saveWorkHygieneRecords,
} from "@/lib/hygieneStorage";
import type { Animal, FacilityHygieneRecord, HealthCheckRecord, HygieneCheckValue, WorkHygieneRecord } from "@/types/gibier";

const autoRecordNote = "個体受入時に自動記録";
const okValue: HygieneCheckValue = "ok";

function matchesAnimal(record: { animalId?: string; animalNumber?: string }, animal: Animal) {
  return record.animalId === animal.id || record.animalId === animal.animalNumber || record.animalNumber === animal.id || record.animalNumber === animal.animalNumber;
}

function hasAutoRecord(records: Array<{ animalId?: string; animalNumber?: string; isAutoGenerated?: boolean; notes?: string }>, animal: Animal) {
  return records.some((record) => matchesAnimal(record, animal) && (record.isAutoGenerated === true || record.notes === autoRecordNote));
}

function createCommonFields(animal: Animal, date: string, checkedBy: string) {
  return [
    { fieldId: "animalNumber", value: animal.animalNumber },
    { fieldId: "date", value: date },
    { fieldId: "checkedBy", value: checkedBy },
  ];
}

export function createAutoHygieneRecordsForAnimal(animal: Animal) {
  const now = new Date().toISOString();
  const date = animal.receivedAt || now;
  const checkedBy = animal.transportedBy || animal.stopBleedingBy || animal.receivedBy || "ジビエ 太郎";

  const facilityRecords = getFacilityHygieneRecords();
  if (!hasAutoRecord(facilityRecords, animal)) {
    const facilityRecord: FacilityHygieneRecord = {
      id: `facility-auto-${animal.id}`,
      date,
      animalId: animal.id,
      animalNumber: animal.animalNumber,
      completed: true,
      isAutoGenerated: true,
      hasIssue: false,
      notes: autoRecordNote,
      checkedBy,
      confirmedBy: checkedBy,
      confirmedAt: date,
      checks: facilityHygieneFormItems.map((item) => ({
        itemId: item.id,
        before: okValue,
        after: okValue,
        note: "",
      })),
      fields: [
        ...createCommonFields(animal, date, checkedBy),
        { fieldId: "confirmedBy", value: checkedBy },
        { fieldId: "confirmedAt", value: date },
      ],
      createdAt: now,
      updatedAt: now,
    };

    saveFacilityHygieneRecords([facilityRecord, ...facilityRecords]);
  }

  const workRecords = getWorkHygieneRecords();
  if (!hasAutoRecord(workRecords, animal)) {
    const workRecord: WorkHygieneRecord = {
      id: `work-auto-${animal.id}`,
      date,
      animalId: animal.id,
      animalNumber: animal.animalNumber,
      completed: true,
      isAutoGenerated: true,
      hasIssue: false,
      notes: autoRecordNote,
      checkedBy,
      confirmedBy: checkedBy,
      confirmedAt: date,
      deviationItems: "該当なし",
      deviationResponse: "",
      checks: workHygieneFormItems.map((item) => ({ itemId: item.id, result: okValue })),
      fields: [
        ...createCommonFields(animal, date, checkedBy),
        { fieldId: "confirmedBy", value: checkedBy },
        { fieldId: "confirmedAt", value: date },
        { fieldId: "deviationItems", value: "該当なし" },
        { fieldId: "deviationResponse", value: "" },
      ],
      createdAt: now,
      updatedAt: now,
    };

    saveWorkHygieneRecords([workRecord, ...workRecords]);
  }

  const healthRecords = getHealthCheckRecords();
  if (!hasAutoRecord(healthRecords, animal)) {
    const healthRecord: HealthCheckRecord = {
      id: `health-auto-${animal.id}`,
      date,
      animalId: animal.id,
      animalNumber: animal.animalNumber,
      workerName: checkedBy,
      completed: true,
      isAutoGenerated: true,
      hasIssue: false,
      notes: autoRecordNote,
      checkedBy,
      receivingDate: date,
      processingDate: date,
      checks: healthCheckFormItems.map((item) => ({
        itemId: item.id,
        receiving: okValue,
        processing: okValue,
      })),
      fields: [
        { fieldId: "animalNumber", value: animal.animalNumber },
        { fieldId: "receivingDate", value: date },
        { fieldId: "processingDate", value: date },
        { fieldId: "workerName", value: checkedBy },
      ],
      createdAt: now,
      updatedAt: now,
    };

    saveHealthCheckRecords([healthRecord, ...healthRecords]);
  }
}
