export type HygieneCheckTiming = "before" | "after" | "receiving" | "processing" | "result";

export type HygieneFormItem = {
  id: string;
  section: string;
  no?: number;
  label: string;
  note?: string;
  timings?: HygieneCheckTiming[];
};

export type TraceabilityFormItem = {
  id: string;
  label: string;
  source: "animal" | "system" | "todo";
  note?: string;
};

const facilityTimings: HygieneCheckTiming[] = ["before", "after"];

export const facilityHygieneFormItems: HygieneFormItem[] = [
  { id: "receiving-floor", section: "荷受室", label: "床の衛生確認", note: "衛生確認は「ほこり」「衛生害虫」「汚れ」の三点とする。", timings: facilityTimings },
  { id: "receiving-ceiling", section: "荷受室", label: "天井の衛生確認", timings: facilityTimings },
  { id: "receiving-wall", section: "荷受室", label: "壁の衛生確認", timings: facilityTimings },
  { id: "receiving-window", section: "荷受室", label: "窓の衛生確認", timings: facilityTimings },
  { id: "receiving-light", section: "荷受室", label: "照明器具の衛生確認", timings: facilityTimings },
  { id: "receiving-hanger", section: "荷受室", label: "吊張機の煮沸消毒・殺菌", timings: facilityTimings },
  { id: "receiving-door-hand", section: "荷受室", label: "開き戸手元の洗浄・殺菌", timings: facilityTimings },
  { id: "receiving-shutter", section: "荷受室", label: "シャッターの洗浄・殺菌", timings: facilityTimings },
  { id: "receiving-drain-box", section: "荷受室", label: "排水升 残渣物の付着・匂いはないか", timings: facilityTimings },
  { id: "receiving-grease-trap", section: "荷受室", label: "グリスラップ 残渣物の付着・匂いはないか", timings: facilityTimings },
  { id: "dismantling-floor", section: "解体室", label: "床の衛生確認", timings: facilityTimings },
  { id: "dismantling-ceiling", section: "解体室", label: "天井の衛生確認", timings: facilityTimings },
  { id: "dismantling-wall", section: "解体室", label: "壁の衛生確認", timings: facilityTimings },
  { id: "dismantling-window", section: "解体室", label: "窓の衛生確認", timings: facilityTimings },
  { id: "dismantling-light", section: "解体室", label: "照明器具の衛生確認", timings: facilityTimings },
  { id: "dismantling-sink", section: "解体室", label: "シンクの衛生管理", timings: facilityTimings },
  { id: "dismantling-hanger", section: "解体室", label: "吊張機の煮沸消毒・殺菌", timings: facilityTimings },
  { id: "dismantling-knife-boil", section: "解体室", label: "包丁の煮沸消毒・殺菌", timings: facilityTimings },
  { id: "dismantling-knife-storage", section: "解体室", label: "包丁の収納", timings: facilityTimings },
  { id: "dismantling-boiler-temp", section: "解体室", label: "煮沸消毒器の温度確認（85℃以上）", timings: facilityTimings },
  { id: "dismantling-door-hand", section: "解体室", label: "開き戸手元の洗浄・殺菌", timings: facilityTimings },
  { id: "dismantling-trash", section: "解体室", label: "ゴミ ゴミ箱は空か", timings: facilityTimings },
  { id: "dismantling-drain", section: "解体室", label: "排水溝 残渣物の付着・匂いはないか", timings: facilityTimings },
  { id: "meat-room-floor", section: "食肉小分室", label: "床の衛生確認", timings: facilityTimings },
  { id: "meat-room-ceiling", section: "食肉小分室", label: "天井の衛生確認", timings: facilityTimings },
  { id: "meat-room-wall", section: "食肉小分室", label: "壁の衛生確認", timings: facilityTimings },
  { id: "meat-room-window", section: "食肉小分室", label: "窓の衛生確認", timings: facilityTimings },
  { id: "meat-room-light", section: "食肉小分室", label: "照明器具の衛生確認", timings: facilityTimings },
  { id: "meat-room-sink", section: "食肉小分室", label: "シンクの衛生管理", timings: facilityTimings },
  { id: "meat-room-table", section: "食肉小分室", label: "作業台の衛生確認", timings: facilityTimings },
  { id: "meat-room-cutting-board", section: "食肉小分室", label: "まな板の衛生確認", timings: facilityTimings },
  { id: "meat-room-knife-boil", section: "食肉小分室", label: "包丁の煮沸消毒・殺菌", timings: facilityTimings },
  { id: "meat-room-knife-storage", section: "食肉小分室", label: "包丁の収納", timings: facilityTimings },
  { id: "meat-room-aging-temp", section: "食肉小分室", label: "熟成庫の温度確認（3℃以下）", timings: facilityTimings },
  { id: "meat-room-aging-hygiene", section: "食肉小分室", label: "熟成庫の衛生確認", timings: facilityTimings },
  { id: "meat-room-door-hand", section: "食肉小分室", label: "開き戸手元の洗浄・殺菌", timings: facilityTimings },
  { id: "meat-room-door-knob", section: "食肉小分室", label: "ドアノブの洗浄・殺菌", timings: facilityTimings },
  { id: "meat-room-trash", section: "食肉小分室", label: "ゴミ ゴミ箱は空か", timings: facilityTimings },
  { id: "meat-room-drain", section: "食肉小分室", label: "排水溝 残渣物の付着・匂いはないか", timings: facilityTimings },
  { id: "packing-floor", section: "包装室", label: "床の衛生確認", timings: facilityTimings },
  { id: "packing-ceiling", section: "包装室", label: "天井の衛生確認", timings: facilityTimings },
  { id: "packing-wall", section: "包装室", label: "壁の衛生確認", timings: facilityTimings },
  { id: "packing-window", section: "包装室", label: "窓の衛生確認", timings: facilityTimings },
  { id: "packing-light", section: "包装室", label: "照明器具の衛生確認", timings: facilityTimings },
  { id: "packing-sink", section: "包装室", label: "シンクの衛生管理", timings: facilityTimings },
  { id: "packing-table", section: "包装室", label: "作業台の衛生確認", timings: facilityTimings },
  { id: "packing-vacuum-operation", section: "包装室", label: "真空パック機の動作確認", timings: facilityTimings },
  { id: "packing-vacuum-sterilize", section: "包装室", label: "真空パック機の殺菌", timings: facilityTimings },
  { id: "packing-metal-operation", section: "包装室", label: "金属探知機の動作確認", timings: facilityTimings },
  { id: "packing-metal-sterilize", section: "包装室", label: "金属探知機の殺菌", timings: facilityTimings },
  { id: "packing-label-operation", section: "包装室", label: "ラベル印刷機の動作確認", timings: facilityTimings },
  { id: "packing-label-sterilize", section: "包装室", label: "ラベル印刷機の殺菌", timings: facilityTimings },
  { id: "packing-fridge-temp", section: "包装室", label: "冷蔵庫の温度確認（3℃以下）", timings: facilityTimings },
  { id: "packing-fridge-hygiene", section: "包装室", label: "冷蔵庫の衛生確認", timings: facilityTimings },
  { id: "packing-freezer-temp", section: "包装室", label: "冷凍庫の温度確認（-25℃以下）", timings: facilityTimings },
  { id: "packing-freezer-hygiene", section: "包装室", label: "冷凍庫の衛生確認", timings: facilityTimings },
  { id: "packing-door-hand", section: "包装室", label: "開き戸手元の洗浄・殺菌", timings: facilityTimings },
  { id: "packing-door-knob", section: "包装室", label: "ドアノブの洗浄・殺菌", timings: facilityTimings },
  { id: "packing-trash", section: "包装室", label: "ゴミ ゴミ箱は空か", timings: facilityTimings },
  { id: "office-floor", section: "事務室", label: "床の衛生確認", timings: facilityTimings },
  { id: "office-ceiling", section: "事務室", label: "天井の衛生確認", timings: facilityTimings },
  { id: "office-wall", section: "事務室", label: "壁の衛生確認", timings: facilityTimings },
  { id: "office-window", section: "事務室", label: "窓の衛生確認", timings: facilityTimings },
  { id: "office-light", section: "事務室", label: "照明器具の衛生確認", timings: facilityTimings },
  { id: "office-desk", section: "事務室", label: "机の衛生確認", timings: facilityTimings },
  { id: "office-kitchen", section: "事務室", label: "炊事台の衛生確認", timings: facilityTimings },
  { id: "office-door-hand", section: "事務室", label: "開き戸手元の洗浄・殺菌", timings: facilityTimings },
  { id: "office-door-knob", section: "事務室", label: "ドアノブの洗浄・殺菌", timings: facilityTimings },
  { id: "office-trash", section: "事務室", label: "ゴミ ゴミ箱は空か", timings: facilityTimings },
  { id: "changing-floor", section: "更衣室", label: "床の衛生確認", timings: facilityTimings },
  { id: "changing-ceiling", section: "更衣室", label: "天井の衛生確認", timings: facilityTimings },
  { id: "changing-wall", section: "更衣室", label: "壁の衛生確認", timings: facilityTimings },
  { id: "changing-window", section: "更衣室", label: "窓の衛生確認", timings: facilityTimings },
  { id: "changing-light", section: "更衣室", label: "照明器具の衛生確認", timings: facilityTimings },
  { id: "toilet-floor", section: "トイレ", label: "床の衛生確認", timings: facilityTimings },
  { id: "toilet-ceiling", section: "トイレ", label: "天井の衛生確認", timings: facilityTimings },
  { id: "toilet-wall", section: "トイレ", label: "壁の衛生確認", timings: facilityTimings },
  { id: "toilet-window", section: "トイレ", label: "窓の衛生確認", timings: facilityTimings },
  { id: "toilet-light", section: "トイレ", label: "照明器具の衛生確認", timings: facilityTimings },
  { id: "toilet-seat", section: "トイレ", label: "便座の洗浄・殺菌", timings: facilityTimings },
  { id: "toilet-door-knob", section: "トイレ", label: "ドアノブの洗浄・殺菌", timings: facilityTimings },
  { id: "toilet-trash", section: "トイレ", label: "ゴミ ゴミ箱は空か", timings: facilityTimings },
  { id: "waste-floor", section: "廃棄物保管庫", label: "床の衛生確認", timings: facilityTimings },
  { id: "waste-ceiling", section: "廃棄物保管庫", label: "天井の衛生確認", timings: facilityTimings },
  { id: "waste-wall", section: "廃棄物保管庫", label: "壁の衛生確認", timings: facilityTimings },
  { id: "waste-window", section: "廃棄物保管庫", label: "窓の衛生確認", timings: facilityTimings },
  { id: "waste-light", section: "廃棄物保管庫", label: "照明器具の衛生確認", timings: facilityTimings },
  { id: "waste-freezer", section: "廃棄物保管庫", label: "冷凍庫の衛生確認", timings: facilityTimings },
  { id: "waste-door-knob", section: "廃棄物保管庫", label: "ドアノブの洗浄・殺菌", timings: facilityTimings },
  { id: "water-faucet", section: "共通 水道", label: "蛇口の洗浄・殺菌", timings: facilityTimings },
  { id: "water-color", section: "共通 水道", label: "水の色は透明か", timings: facilityTimings },
  { id: "water-smell", section: "共通 水道", label: "水の臭いはないか", timings: facilityTimings },
  { id: "water-cloudiness", section: "共通 水道", label: "水の濁りはないか", timings: facilityTimings },
  { id: "water-foreign-matter", section: "共通 水道", label: "水の異物はないか", timings: facilityTimings },
];

export const workHygieneFormItems: HygieneFormItem[] = [
  { id: "dirty-1", section: "汚染区域内作業（1~10 個体受入→放血→剝皮）準清潔区内作業（11~18 内臓摘出）", no: 1, label: "汚染区域専用の長靴に履き替えて作業を実施したか", timings: ["result"] },
  { id: "dirty-2", section: "汚染区域内作業（1~10 個体受入→放血→剝皮）準清潔区内作業（11~18 内臓摘出）", no: 2, label: "長靴の消毒をしてから作業を実施したか", timings: ["result"] },
  { id: "dirty-3", section: "汚染区域内作業（1~10 個体受入→放血→剝皮）準清潔区内作業（11~18 内臓摘出）", no: 3, label: "汚染区域専用の前掛けを着用して作業を実施したか", timings: ["result"] },
  { id: "dirty-4", section: "汚染区域内作業（1~10 個体受入→放血→剝皮）準清潔区内作業（11~18 内臓摘出）", no: 4, label: "放血作業は、軍手ではなく、ゴムやビニ－ル等合成樹脂製の手袋を使用したか", timings: ["result"] },
  { id: "dirty-5", section: "汚染区域内作業（1~10 個体受入→放血→剝皮）準清潔区内作業（11~18 内臓摘出）", no: 5, label: "狩猟個体は捕獲後2時間以内にジビエ処理施設に搬入したか", timings: ["result"] },
  { id: "dirty-6", section: "汚染区域内作業（1~10 個体受入→放血→剝皮）準清潔区内作業（11~18 内臓摘出）", no: 6, label: "血液などにより周囲が汚染されないよう配慮し、運搬車両は使用前後に洗浄したか", timings: ["result"] },
  { id: "dirty-7", section: "汚染区域内作業（1~10 個体受入→放血→剝皮）準清潔区内作業（11~18 内臓摘出）", no: 7, label: "必ず手袋を着用し、必要に応じ頻繁に交換を実施したか", timings: ["result"] },
  { id: "dirty-8", section: "汚染区域内作業（1~10 個体受入→放血→剝皮）準清潔区内作業（11~18 内臓摘出）", no: 8, label: "個体を十分に洗浄してから剝皮作業を実施したか", timings: ["result"] },
  { id: "dirty-9", section: "汚染区域内作業（1~10 個体受入→放血→剝皮）準清潔区内作業（11~18 内臓摘出）", no: 9, label: "剥皮は内側から外側に切開し、剥皮部分の汚染を防止したか", timings: ["result"] },
  { id: "dirty-10", section: "汚染区域内作業（1~10 個体受入→放血→剝皮）準清潔区内作業（11~18 内臓摘出）", no: 10, label: "肛門部、食道部の結紮を行い、腸内容物による汚染を防止したか", timings: ["result"] },
  { id: "dirty-11", section: "汚染区域内作業（1~10 個体受入→放血→剝皮）準清潔区内作業（11~18 内臓摘出）", no: 11, label: "内臓は腸内容物による汚染防止のため傷つけないよう摘出したか", timings: ["result"] },
  { id: "dirty-12", section: "汚染区域内作業（1~10 個体受入→放血→剝皮）準清潔区内作業（11~18 内臓摘出）", no: 12, label: "手指・ナイフなどは必要に応じ洗浄・殺菌を行い、剥皮された部分への汚染防止したか", timings: ["result"] },
  { id: "dirty-13", section: "汚染区域内作業（1~10 個体受入→放血→剝皮）準清潔区内作業（11~18 内臓摘出）", no: 13, label: "放血、結紮、剝皮、内臓摘出の作業移行時使用器具は適正に洗浄・殺菌を実施したか", timings: ["result"] },
  { id: "dirty-14", section: "汚染区域内作業（1~10 個体受入→放血→剝皮）準清潔区内作業（11~18 内臓摘出）", no: 14, label: "複数個体搬入の場合、使用ナイフ、手袋は個体ごとに取り換えられたか", timings: ["result"] },
  { id: "dirty-15", section: "汚染区域内作業（1~10 個体受入→放血→剝皮）準清潔区内作業（11~18 内臓摘出）", no: 15, label: "作業中煮沸消毒器の温度は規定温度（85℃以上）だったか", timings: ["result"] },
  { id: "dirty-16", section: "汚染区域内作業（1~10 個体受入→放血→剝皮）準清潔区内作業（11~18 内臓摘出）", no: 16, label: "剝皮した個体は十分に洗浄・消毒をしたか", timings: ["result"] },
  { id: "dirty-17", section: "汚染区域内作業（1~10 個体受入→放血→剝皮）準清潔区内作業（11~18 内臓摘出）", no: 17, label: "剝皮した個体は速やかに10℃以下となるよう冷却したか", timings: ["result"] },
  { id: "dirty-18", section: "汚染区域内作業（1~10 個体受入→放血→剝皮）準清潔区内作業（11~18 内臓摘出）", no: 18, label: "冷蔵庫（熟成庫）温度は3℃以下になっていたか", timings: ["result"] },
  { id: "clean-1", section: "清潔区域内作業（解体→小分け→計量→真空パック→金属探知→ラベル張り→保存）", no: 1, label: "清潔区域専用の長靴に履き替えて作業を実施したか", timings: ["result"] },
  { id: "clean-2", section: "清潔区域内作業（解体→小分け→計量→真空パック→金属探知→ラベル張り→保存）", no: 2, label: "必ず手袋を着用し、必要に応じ頻繁に交換を行ったか", timings: ["result"] },
  { id: "clean-3", section: "清潔区域内作業（解体→小分け→計量→真空パック→金属探知→ラベル張り→保存）", no: 3, label: "冷蔵庫（熟成庫）温度は3℃以下になっていたか", timings: ["result"] },
  { id: "clean-4", section: "清潔区域内作業（解体→小分け→計量→真空パック→金属探知→ラベル張り→保存）", no: 4, label: "解体・小分け作業専用ナイフを使用したか", timings: ["result"] },
  { id: "clean-5", section: "清潔区域内作業（解体→小分け→計量→真空パック→金属探知→ラベル張り→保存）", no: 5, label: "手指・ナイフなどは必要に応じ洗浄・殺菌を行い汚染を防止したか", timings: ["result"] },
  { id: "clean-6", section: "清潔区域内作業（解体→小分け→計量→真空パック→金属探知→ラベル張り→保存）", no: 6, label: "十分に殺菌・消毒された器具（ナイフ、まな板、作業台）を使用して解体を実施したか", timings: ["result"] },
  { id: "clean-7", section: "清潔区域内作業（解体→小分け→計量→真空パック→金属探知→ラベル張り→保存）", no: 7, label: "作業中煮沸消毒器の温度は規定温度（85℃以上）だったか", timings: ["result"] },
  { id: "clean-8", section: "清潔区域内作業（解体→小分け→計量→真空パック→金属探知→ラベル張り→保存）", no: 8, label: "計量器の衛生は保たれていたか", timings: ["result"] },
  { id: "clean-9", section: "清潔区域内作業（解体→小分け→計量→真空パック→金属探知→ラベル張り→保存）", no: 9, label: "計量器は正しく作動したか", timings: ["result"] },
  { id: "clean-10", section: "清潔区域内作業（解体→小分け→計量→真空パック→金属探知→ラベル張り→保存）", no: 10, label: "真空包装機・真空パックの衛生は保たれていたか", timings: ["result"] },
  { id: "clean-11", section: "清潔区域内作業（解体→小分け→計量→真空パック→金属探知→ラベル張り→保存）", no: 11, label: "真空包装機は正しく作動したか", timings: ["result"] },
  { id: "clean-12", section: "清潔区域内作業（解体→小分け→計量→真空パック→金属探知→ラベル張り→保存）", no: 12, label: "金属探知機の衛生は保たれていたか", timings: ["result"] },
  { id: "clean-13", section: "清潔区域内作業（解体→小分け→計量→真空パック→金属探知→ラベル張り→保存）", no: 13, label: "金属探知機はテストピース（鉄2㎜ ステンレス2㎜）でテストをしたか", timings: ["result"] },
  { id: "clean-14", section: "清潔区域内作業（解体→小分け→計量→真空パック→金属探知→ラベル張り→保存）", no: 14, label: "ラベルは個体番号、部位、製造年月日、消費期限の表示がされているか", timings: ["result"] },
  { id: "clean-15", section: "清潔区域内作業（解体→小分け→計量→真空パック→金属探知→ラベル張り→保存）", no: 15, label: "作業終了後速やかに肉を冷凍したか", timings: ["result"] },
  { id: "clean-16", section: "清潔区域内作業（解体→小分け→計量→真空パック→金属探知→ラベル張り→保存）", no: 16, label: "冷凍庫の温度は温度は-50℃以下になっていたか", timings: ["result"] },
];

export const healthCheckFormItems: HygieneFormItem[] = [
  { id: "condition-1", section: "体調", no: 1, label: "下痢がない", timings: ["receiving", "processing"] },
  { id: "condition-2", section: "体調", no: 2, label: "腹痛がない", timings: ["receiving", "processing"] },
  { id: "condition-3", section: "体調", no: 3, label: "吐き気がない", timings: ["receiving", "processing"] },
  { id: "condition-4", section: "体調", no: 4, label: "熱がない", timings: ["receiving", "processing"] },
  { id: "head-5", section: "頭", no: 5, label: "帽子・紙キャップを着用する", timings: ["receiving", "processing"] },
  { id: "hand-6", section: "手", no: 6, label: "爪を切っているか", timings: ["receiving", "processing"] },
  { id: "hand-7", section: "手", no: 7, label: "アクセサリー・時計を外す", timings: ["receiving", "processing"] },
  { id: "hand-8", section: "手", no: 8, label: "ビニール手袋を常備している", timings: ["receiving", "processing"] },
  { id: "hand-9", section: "手", no: 9, label: "健康診断での異常がないか", timings: ["receiving", "processing"] },
  { id: "hand-10", section: "手", no: 10, label: "手の傷・激しい手荒れはないか", timings: ["receiving", "processing"] },
  { id: "clothes-11", section: "着衣", no: 11, label: "マスクを常備している", timings: ["receiving", "processing"] },
  { id: "clothes-12", section: "着衣", no: 12, label: "白衣・エプロンを着用している", timings: ["receiving", "processing"] },
  { id: "clothes-13", section: "着衣", no: 13, label: "白衣・エプロンは洗濯したものである", timings: ["receiving", "processing"] },
  { id: "clothes-14", section: "着衣", no: 14, label: "長靴を着用している", timings: ["receiving", "processing"] },
  { id: "clothes-15", section: "着衣", no: 15, label: "ズボンのすそがはみ出していない", timings: ["receiving", "processing"] },
  { id: "handwash-16", section: "手洗い", no: 16, label: "作業の開始前は手洗いしたか", timings: ["receiving", "processing"] },
  { id: "handwash-17", section: "手洗い", no: 17, label: "トイレに行った後、手洗いしたか", timings: ["receiving", "processing"] },
  { id: "handwash-18", section: "手洗い", no: 18, label: "温水での手の汚れを落としたか", timings: ["receiving", "processing"] },
  { id: "handwash-19", section: "手洗い", no: 19, label: "洗剤をよく手につけたか", timings: ["receiving", "processing"] },
  { id: "handwash-20", section: "手洗い", no: 20, label: "よく泡立て、指の間、手首、肘の付け根まで洗ったか", timings: ["receiving", "processing"] },
  { id: "handwash-21", section: "手洗い", no: 21, label: "爪の間をよく洗ったか", timings: ["receiving", "processing"] },
  { id: "handwash-22", section: "手洗い", no: 22, label: "ペーパータオルでよく拭いているか", timings: ["receiving", "processing"] },
  { id: "handwash-23", section: "手洗い", no: 23, label: "消毒用アルコール（エタノール70%）で殺菌しているか", timings: ["receiving", "processing"] },
];

export const traceabilityFormItems: TraceabilityFormItem[] = [
  { id: "animal-number", label: "個体番号", source: "animal" },
  { id: "captured-at", label: "捕獲年月日", source: "animal" },
  { id: "processed-at", label: "解体年月日", source: "animal", note: "TODO: 解体年月日の正式な保存先が確定したら差し替える。" },
  { id: "food-hygiene-manager", label: "食品衛生責任者", source: "todo", note: "TODO: 施設設定または帳票入力から取得する。" },
  { id: "filled-by", label: "記入者", source: "animal" },
  { id: "capture-area", label: "捕獲地域", source: "animal" },
  { id: "hunter-initial", label: "捕獲者氏名（イニシャル）", source: "animal" },
  { id: "capture-method", label: "捕獲方法", source: "animal" },
  { id: "damage-area", label: "被弾又は止め刺し行使部位", source: "todo", note: "TODO: 被弾又は止め刺し行使部位の入力欄を後続Stepで確定する。" },
  { id: "sex", label: "性別", source: "animal" },
  { id: "weight", label: "体重（内臓摘出後）", source: "animal" },
  { id: "metal-detector", label: "金属探知機", source: "system", note: "TODO: 金属探知機検査結果の正式な保存先が確定したら差し替える。" },
  { id: "phone-number", label: "電話番号", source: "todo", note: "TODO: 公開用電話番号の保存先が確定したら差し替える。" },
  { id: "heating-storage", label: "加熱用：－１８度以下保存", source: "system" },
];
