export type AccountRole = "owner" | "staff";

export type AnimalSpecies = "deer" | "boar";

export type AnimalSex = "male" | "female" | "unknown";

export type PregnancyStatus = "yes" | "no" | "";

export type AntlerStatus = "none" | "velvet" | "one" | "two" | "three" | "four" | "";

export type EstimatedAge = "one" | "two" | "three" | "four" | "older" | "";

export type ReceivingAbnormalityResult = "no" | "yes";

export type ProcessingAbnormalityResult = "ok" | "abnormal";

export type AnimalAcceptanceDecision = "accepted" | "rejected";

export type ReceivingAbnormalityCheck = {
  itemId: string;
  result: ReceivingAbnormalityResult;
};

export type ProcessingAbnormalityCheck = {
  itemId: string;
  result: ProcessingAbnormalityResult;
  note?: string;
};

export type AnimalStatus =
  | "received"
  | "waiting_processing"
  | "processing"
  | "processed"
  | "in_stock"
  | "waiting_shipment"
  | "shipped"
  | "discarded"
  | "needs_review";

export type AnimalPhotoType = "whole_body" | "damage" | "capture_point" | "carcass" | "meat" | "other";

export type TransportCooling = "yes" | "no" | "";

export type ImpactOrBleedingPart = "head" | "jaw" | "chest_heart" | "abdomen" | "other" | "";

export type BleedingPerformed = "yes" | "no" | "";

export type KnifeSanitationMethod = "alcohol" | "flame" | "";

export type InventoryStorageType = "refrigerated" | "frozen" | "processed";

export type InventoryStatus = "in_stock" | "reserved" | "waiting_shipment" | "shipped" | "discarded";

export type ShipmentStatus = "planned" | "shipped" | "cancelled";

export type PdfExportStatus = "not_exported" | "exported";

export type PdfExportType = "animal_karte" | "traceability";

export type BadgeTone = "default" | "success" | "warning" | "danger" | "muted";

export type OwnershipFields = {
  facility_id?: string;
  created_by?: string;
  updated_by?: string;
};

export type Animal = OwnershipFields & {
  id: string;
  animalNumber: string;
  species: AnimalSpecies;
  sex: AnimalSex;
  pregnancyStatus?: PregnancyStatus;
  antlerStatus?: AntlerStatus;
  estimatedAge?: EstimatedAge;
  weightKg: number;
  capturedAt: string;
  captureLocation: string;
  meshNumber?: string;
  captureMethod: string;
  hunterName: string;
  weather?: string;
  temperatureC?: number | string;
  receivedAt: string;
  transportedBy?: string;
  receivedBy: string;
  stopBleedingBy?: string;
  transportCooling?: TransportCooling;
  impactOrBleedingPart?: ImpactOrBleedingPart;
  bleedingPerformed?: BleedingPerformed;
  knifeSanitationMethod?: KnifeSanitationMethod;
  bleedingStartTime?: string;
  receivingAbnormalityChecks?: ReceivingAbnormalityCheck[];
  processingAbnormalityChecks?: ProcessingAbnormalityCheck[];
  acceptanceDecision?: AnimalAcceptanceDecision;
  acceptanceRejectionReason?: string;
  status: AnimalStatus;
  notes: string;
  hasIssue: boolean;
  createdAt: string;
  updatedAt: string;
};

export type AnimalPhoto = OwnershipFields & {
  id: string;
  animalId: string;
  type: AnimalPhotoType;
  url: string;
  dataUrl?: string;
  label: string;
  createdAt: string;
};

export type InventoryItem = OwnershipFields & {
  id: string;
  animalId: string;
  animalNumber: string;
  partName: string;
  weightKg: number;
  quantity: number;
  storageType: InventoryStorageType;
  status: InventoryStatus;
  lotNumber: string;
  notes?: string;
  createdAt: string;
};

export type ShipmentItem = {
  partName: string;
  weightKg: number;
  quantity: number;
  lotNumber?: string;
};

export type Shipment = OwnershipFields & {
  id: string;
  shipmentNumber: string;
  animalId: string;
  animalNumber: string;
  customerName: string;
  shippedAt: string;
  shippedBy?: string;
  items: ShipmentItem[];
  status: ShipmentStatus;
  traceabilityPdfStatus: PdfExportStatus;
  notes?: string;
};

export type HygieneRecordSummary = {
  date: string;
  facilityInspectionCompleted: boolean;
  workHygieneCompleted: boolean;
  healthCheckCompleted: boolean;
  hasIssue: boolean;
};

export type PdfExportHistory = OwnershipFields & {
  id: string;
  animalId: string;
  animalNumber: string;
  type: PdfExportType;
  fileName: string;
  exportedAt: string;
  exportedBy: string;
};

export type DashboardSummary = {
  todayReceived: number;
  waitingProcessing: number;
  waitingShipment: number;
  needsReview: number;
};

export type HygieneCheckValue = "ok" | "ng" | "not_applicable" | "";

export type HygieneCheckEntry = {
  itemId: string;
  value?: HygieneCheckValue;
  before?: HygieneCheckValue;
  after?: HygieneCheckValue;
  receiving?: HygieneCheckValue;
  processing?: HygieneCheckValue;
  result?: HygieneCheckValue;
  note?: string;
};

export type HygieneFieldEntry = {
  fieldId: string;
  value: string;
};

export type FacilityHygieneRecord = OwnershipFields & {
  id: string;
  date: string;
  animalId?: string;
  animalNumber?: string;
  completed: boolean;
  isAutoGenerated?: boolean;
  hasIssue: boolean;
  notes: string;
  checkedBy: string;
  confirmedBy?: string;
  confirmedAt?: string;
  checks: HygieneCheckEntry[];
  fields: HygieneFieldEntry[];
  createdAt: string;
  updatedAt: string;
};

export type WorkHygieneRecord = OwnershipFields & {
  id: string;
  date: string;
  animalId?: string;
  animalNumber?: string;
  completed: boolean;
  isAutoGenerated?: boolean;
  hasIssue: boolean;
  notes: string;
  checkedBy: string;
  confirmedBy?: string;
  confirmedAt?: string;
  deviationItems?: string;
  deviationResponse?: string;
  checks: HygieneCheckEntry[];
  fields: HygieneFieldEntry[];
  createdAt: string;
  updatedAt: string;
};

export type HealthCheckRecord = OwnershipFields & {
  id: string;
  date: string;
  animalId?: string;
  animalNumber?: string;
  workerName: string;
  completed: boolean;
  isAutoGenerated?: boolean;
  hasIssue: boolean;
  notes: string;
  checkedBy: string;
  receivingDate?: string;
  processingDate?: string;
  checks: HygieneCheckEntry[];
  fields: HygieneFieldEntry[];
  createdAt: string;
  updatedAt: string;
};

export const speciesLabel: Record<AnimalSpecies, string> = {
  deer: "ニホンジカ",
  boar: "イノシシ",
};

export const sexLabel: Record<AnimalSex, string> = {
  male: "オス",
  female: "メス",
  unknown: "不明",
};

export const pregnancyStatusLabel: Record<PregnancyStatus, string> = {
  yes: "あり",
  no: "なし",
  "": "未入力",
};

export const antlerStatusLabel: Record<AntlerStatus, string> = {
  none: "なし",
  velvet: "袋角",
  one: "１本角",
  two: "２本角",
  three: "３本角",
  four: "４本角",
  "": "未入力",
};

export const estimatedAgeLabel: Record<EstimatedAge, string> = {
  one: "１歳",
  two: "２歳",
  three: "３歳",
  four: "４歳",
  older: "それ以上",
  "": "未入力",
};

export const receivingAbnormalityResultLabel: Record<ReceivingAbnormalityResult, string> = {
  no: "いいえ",
  yes: "はい",
};

export const processingAbnormalityResultLabel: Record<ProcessingAbnormalityResult, string> = {
  ok: "問題なし",
  abnormal: "異常あり",
};

export const animalAcceptanceDecisionLabel: Record<AnimalAcceptanceDecision, string> = {
  accepted: "可",
  rejected: "不可",
};

export const receivingAbnormalityItems = [
  { id: "unstable_gait", label: "①足取りがおぼつかない（捕獲時）" },
  { id: "neurological_symptoms", label: "②神経症状を呈し、挙動に異常がある（捕獲時）" },
  { id: "abdominal_shot", label: "③銃で狩猟した個体の場合は腹部に着弾している（捕獲時）" },
  { id: "facial_deformity", label: "④顔面その他に異常な形（奇形・腫瘤等）がある" },
  { id: "external_parasites", label: "⑤ダニ類など外部寄生虫の寄生が著しい" },
  { id: "hair_loss", label: "⑥脱毛が著しい" },
  { id: "emaciation", label: "⑦痩せている度合いが著しい" },
  { id: "trauma_inflammation", label: "⑧大きな外傷や化膿部位、皮膚の炎症やかさぶたが見られる" },
  { id: "subcutaneous_abscesses", label: "⑨皮下に膿を含むできもの（腫瘍）が多くの部位で見られる" },
  { id: "blisters_erosions", label: "⑩口腔、口唇、舌、乳房、ひづめ等に水ぶくれ（水泡）やただれ（びらん、潰瘍）が多く見られる" },
  { id: "diarrhea_soiling", label: "⑪下痢を呈し尻周辺が著しく汚れている" },
  { id: "other_visible_abnormality", label: "⑫その他、外見上明らかな異常がある" },
] as const;

export const processingAbnormalityItems = [
  { id: "whole_body_parasites_soiling", category: "全身", label: "①著しいダニ等の外部寄生虫、糞便汚染等はないか" },
  { id: "whole_body_tumor_abscess_bleeding", category: "全身", label: "②腫瘍、膿瘍、異常な出血等はないか" },
  { id: "organ_heart_valves", category: "内臓", label: "①心臓は切開し、左右の弁等にイボ等の異常はないか" },
  { id: "organ_heart_muscle", category: "内臓", label: "②心臓は切開し、心臓の筋肉断面に白斑等の異常はないか" },
  { id: "organ_lymph_nodes", category: "内臓", label: "③リンパ節の大きさ、硬さ、色、臭い等に異常はないか" },
  { id: "organ_blood", category: "内臓", label: "④血液の色や粘性に異常はないか" },
  { id: "organ_surface_cut", category: "内臓", label: "⑤表面や断面に白色点、変色部分等はないか" },
  { id: "organ_parasites", category: "内臓", label: "⑥肝臓や肺等に寄生虫はいないか" },
  { id: "organ_fluid", category: "内臓", label: "⑦胸腔内、腹腔内に異常に液が溜まっていないか" },
  { id: "organ_foreign_body", category: "内臓", label: "⑧銃弾等の異物はないか" },
  { id: "organ_other", category: "内臓", label: "⑨その他、内臓の大きさ、硬さ、色、臭い等の異常はないか" },
  { id: "carcass_watery", category: "枝肉", label: "①筋肉や脂肪は水っぽくないか" },
  { id: "carcass_joints", category: "枝肉", label: "②関節は腫れていないか" },
  { id: "carcass_parasites", category: "枝肉", label: "③肉眼で筋肉中に寄生虫が確認できないか" },
  { id: "carcass_foreign_body", category: "枝肉", label: "④銃弾等の異物はないか" },
  { id: "carcass_other", category: "枝肉", label: "⑤大きさ、硬さ、色、臭い等の異常はないか" },
  { id: "other_clear_abnormality", category: "その他", label: "その他、明らかな異常はないか" },
] as const;

export const transportCoolingLabel: Record<TransportCooling, string> = {
  yes: "有",
  no: "無",
  "": "未入力",
};

export const impactOrBleedingPartLabel: Record<ImpactOrBleedingPart, string> = {
  head: "頭部",
  jaw: "顎部",
  chest_heart: "胸部（心臓）",
  abdomen: "腹部",
  other: "その他",
  "": "未入力",
};

export const bleedingPerformedLabel: Record<BleedingPerformed, string> = {
  yes: "あり",
  no: "なし",
  "": "未入力",
};

export const knifeSanitationMethodLabel: Record<KnifeSanitationMethod, string> = {
  alcohol: "アルコール",
  flame: "火炎",
  "": "未入力",
};

export const animalStatusLabel: Record<AnimalStatus, string> = {
  received: "受入済",
  waiting_processing: "処理待ち",
  processing: "加工中",
  processed: "処理済",
  in_stock: "在庫保管",
  waiting_shipment: "出荷待ち",
  shipped: "出荷済",
  discarded: "廃棄",
  needs_review: "要確認",
};

export const animalStatusBadgeTone: Record<AnimalStatus, BadgeTone> = {
  received: "default",
  waiting_processing: "warning",
  processing: "default",
  processed: "success",
  in_stock: "success",
  waiting_shipment: "warning",
  shipped: "success",
  discarded: "danger",
  needs_review: "danger",
};

export const pdfTypeLabel: Record<PdfExportType, string> = {
  animal_karte: "個体カルテPDF",
  traceability: "トレーサビリティPDF",
};
